name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: coursier/cache-action@v6.3
    - name: Build
      uses: VirtusLab/scala-cli-setup@main
      run: |
        scala-cli fmt --check . || (
          echo "To format code run"
          echo "  scala-cli fmt ."
          exit 1
        )
        scala-cli .github/scripts/package.sc

    - name: Deploy
      uses: actions/upload-artifact@v3
      with:
        name: launchers
        path: artifacts
        if-no-files-found: error
        retention-days: 2
