name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - assets/*
      - .pre-commit-config.yaml
      - .scalafmt.conf

jobs:
  compile:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Coursier
        uses: coursier/cache-action@v6.3

      - name: Setup scala-cli
        uses: VirtusLab/scala-cli-setup@main

      - name: Format
        run: |
          scala-cli fmt --check . || (
            echo "To format code run"
            echo "  scala-cli fmt ."
            exit 1
          )

      - name: Compile
        run: scala-cli compile .
